<a href="https://colab.research.google.com/github/vovsiienko/IT496_Course_acitvities/blob/master/IT496_ViktoriiaO_CPM_PERT_Shortened.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import pandas as pd
import numpy as np
import tensorflow_probability as tfp
tfd=tfp.distributions

simulationDF=pd.read_csv('/content/drive/MyDrive/IT496/simulationDataset.csv')

simulationDF.head(2)

,A,B,C,D,E,F,G,H,I,J,EOP
0,6.779389,4.518081,4.588156,2.693674,5.198787,4.360078,6.896625,1.181040,13.967291,2.581787,NaN
1,6.653130,4.175826,2.546335,2.622374,5.509677,5.459227,3.933105,5.066621,19.884926,2.304569,NaN

In [65]:
paths = ['ADEJ','BCDEJ','BCFGJ', 'BCFHJ','BI']
pathsDF=pd.DataFrame(columns=paths)
ADEJ=[]
BCDEJ=[]
BCFGJ=[]
BCFHJ=[]
BI=[]


for index, row in simulationDF.iterrows():
  ADEJ.append(row['A']+row['D']+row['E']+row['J'])
  BCDEJ.append(row['B']+row['C']+row['D']+row['E']+row['J'])
  BCFGJ.append(row['B']+row['C']+row['F']+row['G']+row['J'])
  BCFHJ.append(row['B']+row['C']+row['F']+row['H']+row['J'])
  BI.append(row['B']+row['I'])

pathsDF['ADEJ'] = ADEJ
pathsDF['BCDEJ'] = BCDEJ
pathsDF['BCFGJ'] = BCFGJ
pathsDF['BCFHJ'] = BCFHJ
pathsDF['BI'] = BI
pathsDF['maxElement'] = pathsDF.idxmax(axis=1)

pathsDF.head(2)

        ADEJ      BCDEJ      BCFGJ      BCFHJ         BI maxElement
0  17.253636  19.580484  22.944727  17.229141  18.485372      BCFGJ
1  17.089749  17.158780  18.419062  19.552577  24.060752         BI

In [66]:
#getting No of cases for path with Max value
cases = pathsDF['maxElement'].value_counts() 

print(cases)

BCDEJ    34074
BCFGJ    25620
BI       21770
BCFHJ    14629
ADEJ      3907
Name: maxElement, dtype: int64

In [67]:
#percent of max value occurance for each path 

percentage = cases*100/100000
print(percentage)

BCDEJ    34.074
BCFGJ    25.620
BI       21.770
BCFHJ    14.629
ADEJ      3.907
Name: maxElement, dtype: float64

In [ ]:
#get the maximum